# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='age',
            field=models.IntegerField(default=18, max_length=3),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='email',
            field=models.EmailField(default='xxx@xx.com', max_length=254),
        ),
    ]
